<img height="100" src="logotmg.png" width="900" alt="Talia Morchi" id="tmg_logo" title="Data Analyst Course">
<center><h1><u>Welcome to the python for data analysis course </u></h1></center><center><h2>Class 6</h2></center>

## Modules
As our program and functionality grows, we can keep it shorter and easy to maintenance by using Modules. 

We can define our most used functions in a module and import it, instead of copying their definitions into different programs

#### How to create a mudule
1. write code (functions) and save the file as file_name.py

    File > Download as > python (.py)


2. Import the functionality into that code into new workbooks with 'import'

#### How to import module
When module in the same folder as the notebook:
* from **module_name** import **functionality_name**

When module in another folder:
* import sys
* sys.path.append (r'C:/Users/TaliaMorchi/Desktop/Python/Gstat/Lesson_6/Modules/')
* from **module_name** import **functionality_name**

In [1]:
import pandas as pd
import numpy as np

In [2]:
# Run these lines only if the module is not in the same folder as the notebook
# sys.path.append(r'C:/Users/TaliaMorchi/Desktop/Python/Gstat/Lesson_6/Modules/')

import sys

sys.path.append('Modules/')

In [3]:
# Import functionality from the module
from Py_MSSql import Py_MSSql

## Connect to MSSql and run queries
* we are going to use class called Py_MSSql which i built to simplify your use of MSSql with Python

#### 1. initialize Py_MSSql instance (from class) - constructor (special method)

In [4]:
# define the connection using Py_MSSql module
# !! Run the SQL script file name 'Create_db.sql' to create TutorialDB database !!

server = 'localhost\\SQLEXPRESS;Trusted_Connection=True;' #' Integrated Security=True;'
database = 'TutorialDB'

py_mssql = Py_MSSql(server=server,database=database)

#### 2. From DataFrame to MSSQL table
    a. Create the table and populate it 
    b. Query it with SQL Server Management Studio

In [5]:
# Import data from csv to DataFrame
df = pd.read_csv('titanic_train.csv')

In [6]:
# New table in mssql name
tbl_name = 'tbl_titanic'

In [7]:
# Check if exist, and drop, so we can re-create the table
py_mssql.drop_table_if_exist(tbl_name)

IF OBJECT_ID('dbo.tbl_titanic', 'U') IS NOT NULL DROP TABLE dbo.tbl_titanic

In [8]:
# Create new table in same stucture as DateFrame variable
py_mssql.create_tbl_from_df (df,tbl_name)

CREATE TABLE tbl_titanic (PassengerId NUMERIC(18,10), Survived NUMERIC(18,10), Pclass NUMERIC(18,10), Name VARCHAR(164), Sex VARCHAR(12), Age NUMERIC(18,10), SibSp NUMERIC(18,10), Parch NUMERIC(18,10), Ticket VARCHAR(36), Fare NUMERIC(18,10), Cabin VARCHAR(30), Embarked VARCHAR(2))

In [9]:
# Insert date to the table we created in MSSQL, from out DataFrame 
py_mssql.insert_into_tbl_from_df (df,tbl_name)

?,?,?,?,?,?,?,?,?,?,?,?, 90
INSERT QUERY:INSERT INTO tbl_titanic (PassengerId, Survived, Pclass, Name, Sex, Age, SibSp, Parch, Ticket, Fare, Cabin, Embarked) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)

True

#### 3. From MSSQL table to DataFrame

In [10]:
age = "30"
where_cls = " and name like '%Mrs%'"

sql_query = "select * from tbl_titanic where age >" + age + where_cls
sql_query

# new_df = py_mssql.read_sql_query(sql_query)
# new_df.head()

"select * from tbl_titanic where age >30 and name like '%Mrs%'"

In [11]:
py_mssql.close()

<img height="100" src="time_to_practice.png" width="200" alt="Hands on" id="prc_time" title="Data Analyst Course">
<center><h1>Home Practice 6</h1></center>

#### MSSql integration: build diabets table using python

1. read the diabetes csv file (in this lesson folder)


2. filter only Outcome=1


3. build sql table from df (table 'diabetes')


4. read from new created table to new df:
    * only columns Glucose,BloodPressure, DiabetesPedigreeFunction, Age, Outcome	
    * only BloodPressure above 80
    
    
5. group by age, aggregate over blood pressure: mean, std, min, max

#### MSSql integration: build diabets table using python - solution

1. read the diabetes csv file (in this lesson folder)


2. filter only Outcome=1


3. build sql table from df (table 'diabetes')


4. read from new created table to new df:
    * only columns Glucose,BloodPressure, DiabetesPedigreeFunction, Age, Outcome	
    * only BloodPressure above 80
    
    
5. group by age, aggregate over blood pressure: mean, std, min, max

In [12]:
import pandas as pd
import pyodbc
import sys

sys.path.append('Modules/')
from Py_MSSql import Py_MSSql

In [13]:
# define the connection using Py_MSSql module
# !! Run the SQL script file name 'Create_db.sql' to create TutorialDB database !!

server = 'localhost\\SQLEXPRESS;Trusted_Connection=True;' #' Integrated Security=True;'
database = 'TutorialDB'

py_mssql = Py_MSSql(server=server,database=database)

In [14]:
# 1
df = pd.read_csv('diabetes.csv')
df.head(3)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1

In [15]:
# 2
mask = df['Outcome'] == 1
df = df[mask]
df.head(3)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
2,8,183,64,0,0,23.3,0.672,32,1
4,0,137,40,35,168,43.1,2.288,33,1

In [16]:
# 3
tbl_name = 'diabetes'

# Check if exist, and drop, so we can re-create the table
py_mssql.drop_table_if_exist(tbl_name)

# Create new table in same stucture as DateFrame variable
py_mssql.create_tbl_from_df (df,tbl_name)

# Insert date to the table we created in MSSQL, from out DataFrame 
py_mssql.insert_into_tbl_from_df (df,tbl_name)

IF OBJECT_ID('dbo.diabetes', 'U') IS NOT NULL DROP TABLE dbo.diabetes
CREATE TABLE diabetes (Pregnancies NUMERIC(18,10), Glucose NUMERIC(18,10), BloodPressure NUMERIC(18,10), SkinThickness NUMERIC(18,10), Insulin NUMERIC(18,10), BMI NUMERIC(18,10), DiabetesPedigreeFunction NUMERIC(18,10), Age NUMERIC(18,10), Outcome NUMERIC(18,10))
?,?,?,?,?,?,?,?,?, 104
INSERT QUERY:INSERT INTO diabetes (Pregnancies, Glucose, BloodPressure, SkinThickness, Insulin, BMI, DiabetesPedigreeFunction, Age, Outcome) VALUES(?,?,?,?,?,?,?,?,?)

True

In [17]:
# 4
sql_query = ''' select  Glucose,
                        BloodPressure, 
                        DiabetesPedigreeFunction,
                        Age, 
                        Outcome
                from diabetes 
                where BloodPressure > 80 '''


sdf = py_mssql.read_sql_query(sql_query)
sdf.head()

   Glucose  BloodPressure  DiabetesPedigreeFunction   Age  Outcome
0    125.0           96.0                     0.232  54.0      1.0
1    118.0           84.0                     0.551  31.0      1.0
2    196.0           90.0                     0.451  41.0      1.0
3    143.0           94.0                     0.254  51.0      1.0
4    171.0          110.0                     0.721  54.0      1.0

In [18]:
# 5
new_df = sdf.groupby('Age').agg({'BloodPressure': ['mean', 'std', 'min', 'max']})
new_df

     BloodPressure
              mean        std    min    max
Age
21.0     90.000000        NaN   90.0   90.0
22.0     84.500000   1.914854   82.0   86.0
23.0     88.000000   2.828427   86.0   90.0
24.0     86.500000   2.121320   85.0   88.0
25.0     82.000000        NaN   82.0   82.0
26.0     99.000000  15.556349   88.0  110.0
27.0     88.000000   8.485281   82.0   94.0
28.0     98.000000        NaN   98.0   98.0
29.0     85.000000   1.414214   84.0   86.0
31.0     87.000000   4.242641   84.0   90.0
32.0     88.000000   4.000000   84.0   92.0
33.0     98.000000        NaN   98.0   98.0
35.0     87.000000   4.242641   84.0   90.0
36.0     84.000000   3.464102   82.0   88.0
37.0     90.000000  10.677078   82.0  108.0
38.0     87.000000   1.414214   86.0   88.0
40.0     88.000000   0.000000   88.0   88.0
41.0     90.500000   9.433981   84.0  104.0
42.0     86.666667   3.055050   84.0   90.0
43.0     92.000000  10.066446   82.0  106.0
44.0    114.000000        NaN  114.0  114.0
45.0     95.000000   8.082904   84.0  102.0
46.0     82.000000        NaN   82.0   82.0
47.0     86.000000        NaN   86.0   86.0
49.0     86.500000   2.121320   85.0   88.0
50.0     82.000000        NaN   82.0   82.0
51.0     87.333333   5.773503   84.0   94.0
52.0     92.666667   9.865766   86.0  104.0
53.0     87.000000   1.414214   86.0   88.0
54.0    103.000000   9.899495   96.0  110.0
56.0     85.000000        NaN   85.0   85.0
58.0     84.666667   4.618802   82.0   90.0
61.0     92.000000        NaN   92.0   92.0
62.0     84.000000        NaN   84.0   84.0
66.0     91.000000   1.414214   90.0   92.0
70.0     82.000000        NaN   82.0   82.0