<img height="100" src="logotmg.png" width="900" alt="Talia Morchi" id="tmg_logo" title="Data Analyst Course">
<center><h1><u>Welcome to the python for data analysis course </u></h1></center><center><h2>Class 6</h2></center>

## Install pyodbc

#### The pyodbc library must be installed once, and then we will only import it into the workbook
* Start >> Anaconda prompt >> write the following command, and press Enter:
       pip install pyodbc

## Import Basic libraries

In [1]:
# If pyodbc is not installed, please install it first using pip install pyodbc
import pandas as pd
import pyodbc

## Connection to SQL

#### Define the connection to MSSQL

In [2]:
# Server = SQL server name
# Database = The name of the db we want to connect to

conn = pyodbc.connect ( 'Driver={SQL Server};'
                        'Server=localhost\\SQLEXPRESS;'
                        'Database=AdventureWorks2019;'
                        'Trusted_Connection=yes;' )

## Retrive data from MSSQL table
sql_query_result = pd.read_sql_query('SQL Query' ,conn)

#### Basic queries

In [3]:
# Read SQL query results into a DataFrame
# Simple example
query = '''SELECT * 
           FROM Sales.SalesOrderHeader'''

sql_query_result = pd.read_sql_query(query, conn)

In [4]:
# Receive results into DataFrame object
print (type (sql_query_result))

<class 'pandas.core.frame.DataFrame'>

In [5]:
sql_query_result.head(3)

,SalesOrderID,RevisionNumber,OrderDate,DueDate,ShipDate,Status,OnlineOrderFlag,SalesOrderNumber,PurchaseOrderNumber,AccountNumber,...,CreditCardID,CreditCardApprovalCode,CurrencyRateID,SubTotal,TaxAmt,Freight,TotalDue,Comment,rowguid,ModifiedDate
0,43659,8,2011-05-31,2011-06-12,2011-06-07,5,False,SO43659,PO522145787,10-4020-000676,...,16281.0,105041Vi84182,NaN,20565.6206,1971.5149,616.0984,23153.2339,None,79B65321-39CA-4115-9CBA-8FE0903E12E6,2011-06-07
1,43660,8,2011-05-31,2011-06-12,2011-06-07,5,False,SO43660,PO18850127500,10-4020-000117,...,5618.0,115213Vi29411,NaN,1294.2529,124.2483,38.8276,1457.3288,None,738DC42D-D03B-48A1-9822-F95A67EA7389,2011-06-07
2,43661,8,2011-05-31,2011-06-12,2011-06-07,5,False,SO43661,PO18473189620,10-4020-000442,...,1346.0,85274Vi6854,4.0,32726.4786,3153.7696,985.5530,36865.8012,None,D91B9131-18A4-4A11-BC3A-90B6F53E9D74,2011-06-07

In [6]:
# Triple quotes preserve the text structure
query = '''SELECT BusinessEntityID,
                  FirstName,
                  LastName,
                  ModifiedDate
           FROM   Person.Person
           WHERE  BusinessEntityID = 6 '''

pd.read_sql_query(query, conn)

   BusinessEntityID FirstName LastName            ModifiedDate
0                 6     Jason    Globe 2020-11-12 10:57:49.890

In [7]:
# Example with more complex query
query = '''SELECT   h.SalesOrderID,
                    h.OrderDate,
                    d.ProductID,
                    d.OrderQty,
                    d.LineTotal
           FROM Sales.SalesOrderHeader h
               JOIN Sales.SalesOrderDetail d
                   ON h.SalesOrderID = d.SalesOrderID
           WHERE YEAR(h.OrderDate) = 2013'''

pd.read_sql_query(query ,conn)

       SalesOrderID  OrderDate  ProductID  OrderQty  LineTotal
0             49181 2013-01-01        794         1  2181.5625
1             49182 2013-01-01        790         1  2443.3500
2             49183 2013-01-01        791         1  2443.3500
3             49184 2013-01-01        784         1  2049.0982
4             49185 2013-01-01        784         1  2049.0982
...             ...        ...        ...       ...        ...
56568         63360 2013-12-31        998         1   539.9900
56569         63360 2013-12-31        872         1     8.9900
56570         63361 2013-12-31        955         1  2384.0700
56571         63362 2013-12-31        966         1  2384.0700
56572         63362 2013-12-31        711         1    34.9900

[56573 rows x 5 columns]

## Cursor object
The cursor object that gives us the ability to have multiple seperate working environments through the same connection to the database. By default the cursor is created using the default cursor class.

#### Queries with parameters

In order to retrieve results of query with parameters, we'll follow the next steps:
1.  cursor = conn.cursor()
2.  query = 'Query syntax'
3.  cursor.execute (query)
4.  if just recsive results >>   results = cursor.fetchall() 
5.  if changes the data >>  conn.commit()
    
    
Another way is to concatenate text to create a regular text query

In [8]:
# Create cursor object that is bound to the connection 
cursor = conn.cursor()

#### Change sql data

In [9]:
# The question marks (?), will be replaced by the values of a parameter that will be sent

query = '''UPDATE Person.Person
           SET    FirstName = ?, LastName = ?, ModifiedDate=getdate()
           WHERE  BusinessEntityID = ? ;'''

In [10]:
# Execute the query and send the parameters to replace the '?'

cursor.execute (query,['Jason','Globe',6])
# cursor.execute (query,['Jossef','Goldberg',6])

In [11]:
# Commit the changes in the SQL DB
# We will use commit() only if there are changes in the data
conn.commit()

In [12]:
# Check if the value changed

query = '''SELECT BusinessEntityID,
                  FirstName,
                  LastName,
                  ModifiedDate
           FROM   Person.Person
           WHERE  BusinessEntityID = 6 '''

pd.read_sql_query(query, conn)

   BusinessEntityID FirstName LastName            ModifiedDate
0                 6     Jason    Globe 2020-11-12 12:13:23.620

#### Retrive data using query with parameters

In [13]:
# Displays the distance of the sale from the annual sales average, only for existing customers in 2013
query = '''SELECT SalesOrderID,
                  TotalDue,
                  TotalDue - ( SELECT avg (TotalDue)
                               FROM Sales.SalesOrderHeader h
                               WHERE year (OrderDate) = ?) DistFromAvg
           FROM   sales.SalesOrderHeader
           WHERE  year (OrderDate) = ? and
                  CustomerID in ( SELECT distinct CustomerID
                                  FROM   Sales.SalesOrderHeader
                                  WHERE  year (OrderDate) < ?
                                      );'''

In [14]:
year = 2013

In [15]:
# Prepare and execute a database query or command
cursor.execute (query,[year, year, year])

In [16]:
# Fetch all remaining rows of a query result
# We use fetchall when we just retreive data (do not update)
rows = cursor.fetchall()

In [17]:
# The data received in a list of rows object
print(type(rows))
print(type(rows[0]))

<class 'list'>
<class 'pyodbc.Row'>

In [18]:
rows

[(49443, Decimal('76.2853'), Decimal('-3376.3933')),
 (49444, Decimal('7333.3076'), Decimal('3880.6290')),
 (49445, Decimal('3173.9282'), Decimal('-278.7504')),
 (49446, Decimal('15340.6533'), Decimal('11887.9747')),
 (49447, Decimal('120.2717'), Decimal('-3332.4069')),
 (49448, Decimal('1435.1443'), Decimal('-2017.5343')),
 (49449, Decimal('50.7737'), Decimal('-3401.9049')),
 (49450, Decimal('36854.3018'), Decimal('33401.6232')),
 (49451, Decimal('2921.0624'), Decimal('-531.6162')),
 (49452, Decimal('1473.8636'), Decimal('-1978.8150')),
 (49453, Decimal('1399.4512'), Decimal('-2053.2274')),
 (49454, Decimal('6972.6272'), Decimal('3519.9486')),
 (49455, Decimal('528.9880'), Decimal('-2923.6906')),
 (49456, Decimal('700.6543'), Decimal('-2752.0243')),
 (49457, Decimal('76.2966'), Decimal('-3376.3820')),
 (49458, Decimal('223.6817'), Decimal('-3228.9969')),
 (49459, Decimal('732.9386'), Decimal('-2719.7400')),
 (49460, Decimal('2464.5599'), Decimal('-988.1187')),
 (49461, Decimal('203.0945'), Decimal('-3249.5841')),
 (49462, Decimal('732.9386'), Decimal('-2719.7400')),
 (49463, Decimal('2857.9658'), Decimal('-594.7128')),
 (49464, Decimal('38544.2101'), Decimal('35091.5315')),
 (49465, Decimal('46233.4899'), Decimal('42780.8113')),
 (49466, Decimal('9715.9819'), Decimal('6263.3033')),
 (49467, Decimal('43073.1966'), Decimal('39620.5180')),
 (49468, Decimal('41071.0348'), Decimal('37618.3562')),
 (49469, Decimal('752.6697'), Decimal('-2700.0089')),
 (49470, Decimal('613.7951'), Decimal('-2838.8835')),
 (49471, Decimal('2843.6532'), Decimal('-609.0254')),
 (49472, Decimal('16694.6929'), Decimal('13242.0143')),
 (49473, Decimal('15563.5382'), Decimal('12110.8596')),
 (49474, Decimal('2783.8218'), Decimal('-668.8568')),
 (49476, Decimal('19966.9228'), Decimal('16514.2442')),
 (49477, Decimal('7934.8207'), Decimal('4482.1421')),
 (49478, Decimal('2066.2437'), Decimal('-1386.4349')),
 (49479, Decimal('90736.4249'), Decimal('87283.7463')),
 (49480, Decimal('51410.1775'), Decimal('47957.4989')),
 (49481, Decimal('41495.6979'), Decimal('38043.0193')),
 (49482, Decimal('5639.0301'), Decimal('2186.3515')),
 (49483, Decimal('6907.6179'), Decimal('3454.9393')),
 (49484, Decimal('23171.2514'), Decimal('19718.5728')),
 (49485, Decimal('97224.9592'), Decimal('93772.2806')),
 (49486, Decimal('4760.8924'), Decimal('1308.2138')),
 (49487, Decimal('1536.6916'), Decimal('-1915.9870')),
 (49488, Decimal('35532.3404'), Decimal('32079.6618')),
 (49489, Decimal('13064.6795'), Decimal('9612.0009')),
 (49490, Decimal('49850.6903'), Decimal('46398.0117')),
 (49491, Decimal('207.7582'), Decimal('-3244.9204')),
 (49492, Decimal('36653.6393'), Decimal('33200.9607')),
 (49493, Decimal('4760.8924'), Decimal('1308.2138')),
 (49494, Decimal('21398.1905'), Decimal('17945.5119')),
 (49495, Decimal('27280.9721'), Decimal('23828.2935')),
 (49496, Decimal('49267.5037'), Decimal('45814.8251')),
 (49497, Decimal('11637.7369'), Decimal('8185.0583')),
 (49498, Decimal('64243.0161'), Decimal('60790.3375')),
 (49499, Decimal('36830.6141'), Decimal('33377.9355')),
 (49500, Decimal('605.2734'), Decimal('-2847.4052')),
 (49501, Decimal('53243.9979'), Decimal('49791.3193')),
 (49502, Decimal('46837.3357'), Decimal('43384.6571')),
 (49503, Decimal('3806.8206'), Decimal('354.1420')),
 (49504, Decimal('22143.7092'), Decimal('18691.0306')),
 (49505, Decimal('25.3868'), Decimal('-3427.2918')),
 (49506, Decimal('927.0576'), Decimal('-2525.6210')),
 (49507, Decimal('30370.4587'), Decimal('26917.7801')),
 (49508, Decimal('1550.1489'), Decimal('-1902.5297')),
 (49509, Decimal('101069.7604'), Decimal('97617.0818')),
 (49510, Decimal('53013.6422'), Decimal('49560.9636')),
 (49511, Decimal('2644.9402'), Decimal('-807.7384')),
 (49512, Decimal('21739.8473'), Decimal('18287.1687')),
 (49513, Decimal('28969.4128'), Decimal('25516.7342')),
 (49514, Decimal('25.3868'), Decimal('-3427.2918')),
 (49515, Decimal('33437.3046'), Decimal('29984.6260')),
 (49516, Decimal('1483.9807'), Decimal('-1968.6979')),
 (49517, Decimal('3173.9282'), Decimal('-278.7504')),
 (49518, Decimal('35245.7300'), Decimal('31793.0514')),
 (49519, Decimal('104.7480'), Decimal('-3347.9306')),
 (49520, Decimal('2921.0624'), Decimal('-531.6162')),
 (49521, Decimal('37425.9496'), Decimal('33973.2710')),
 (49522, Decimal('1806.6519'), Decimal('-1646.0267')),
 (49523, Decimal('25447.5692'), Decimal('21994.8906')),
 (49524, Decimal('4406.9804'), Decimal('954.3018')),
 (49525, Decimal('1586.9642'), Decimal('-1865.7144')),
 (49526, Decimal('2644.9402'), Decimal('-807.7384')),
 (49527, Decimal('39318.2142'), Decimal('35865.5356')),
 (49528, Decimal('900.4358'), Decimal('-2552.2428')),
 (49529, Decimal('471.5282'), Decimal('-2981.1504')),
 (49530, Decimal('1840.3330'), Decimal('-1612.3456')),
 (49531, Decimal('4760.8924'), Decimal('1308.2138')),
 (49532, Decimal('45386.3704'), Decimal('41933.6918')),
 (49533, Decimal('29798.6159'), Decimal('26345.9373')),
 (49534, Decimal('7934.8207'), Decimal('4482.1421')),
 (49535, Decimal('228.5340'), Decimal('-3224.1446')),
 (49536, Decimal('447.3633'), Decimal('-3005.3153')),
 (49537, Decimal('528.9880'), Decimal('-2923.6906')),
 (49538, Decimal('26312.6236'), Decimal('22859.9450')),
 (49539, Decimal('4269.7398'), Decimal('817.0612')),
 (49540, Decimal('19449.7361'), Decimal('15997.0575')),
 (49541, Decimal('41265.4765'), Decimal('37812.7979')),
 (49542, Decimal('2844.9019'), Decimal('-607.7767')),
 (49543, Decimal('236.3547'), Decimal('-3216.3239')),
 (49544, Decimal('458.1082'), Decimal('-2994.5704')),
 (49545, Decimal('471.2173'), Decimal('-2981.4613')),
 (49546, Decimal('126.9341'), Decimal('-3325.7445')),
 (49547, Decimal('2798.9022'), Decimal('-653.7764')),
 (49548, Decimal('7405.8326'), Decimal('3953.1540')),
 (49821, Decimal('88059.1057'), Decimal('84606.4271')),
 (49822, Decimal('36282.6588'), Decimal('32829.9802')),
 (49823, Decimal('4759.4299'), Decimal('1306.7513')),
 (49824, Decimal('50.1121'), Decimal('-3402.5665')),
 (49825, Decimal('37838.6417'), Decimal('34385.9631')),
 (49826, Decimal('83298.3584'), Decimal('79845.6798')),
 (49827, Decimal('44228.1046'), Decimal('40775.4260')),
 (49828, Decimal('99507.5528'), Decimal('96054.8742')),
 (49829, Decimal('1903.6275'), Decimal('-1549.0511')),
 (49830, Decimal('516.5278'), Decimal('-2936.1508')),
 (49831, Decimal('54010.8625'), Decimal('50558.1839')),
 (49832, Decimal('40783.0899'), Decimal('37330.4113')),
 (49833, Decimal('44663.0076'), Decimal('41210.3290')),
 (49834, Decimal('4875.3573'), Decimal('1422.6787')),
 (49835, Decimal('237.8435'), Decimal('-3214.8351')),
 (49836, Decimal('51314.2241'), Decimal('47861.5455')),
 (49837, Decimal('100902.4370'), Decimal('97449.7584')),
 (49838, Decimal('6773.2996'), Decimal('3320.6210')),
 (49839, Decimal('8904.0200'), Decimal('5451.3414')),
 (49840, Decimal('2400.7201'), Decimal('-1051.9585')),
 (49841, Decimal('49071.5565'), Decimal('45618.8779')),
 (49842, Decimal('366.4694'), Decimal('-3086.2092')),
 (49843, Decimal('90675.5705'), Decimal('87222.8919')),
 (49844, Decimal('84666.0149'), Decimal('81213.3363')),
 (49845, Decimal('4760.8924'), Decimal('1308.2138')),
 (49847, Decimal('315.0005'), Decimal('-3137.6781')),
 (49848, Decimal('66757.2973'), Decimal('63304.6187')),
 (49849, Decimal('55388.0259'), Decimal('51935.3473')),
 (49850, Decimal('6044.7771'), Decimal('2592.0985')),
 (49851, Decimal('41906.4087'), Decimal('38453.7301')),
 (49852, Decimal('7558.4032'), Decimal('4105.7246')),
 (49853, Decimal('4533.9145'), Decimal('1081.2359')),
 (49854, Decimal('755.2447'), Decimal('-2697.4339')),
 (49855, Decimal('40654.7297'), Decimal('37202.0511')),
 (49856, Decimal('97091.1112'), Decimal('93638.4326')),
 (49857, Decimal('50.1121'), Decimal('-3402.5665')),
 (49858, Decimal('528.9880'), Decimal('-2923.6906')),
 (49859, Decimal('3250.2136'), Decimal('-202.4650')),
 (49860, Decimal('42800.3045'), Decimal('39347.6259')),
 (49861, Decimal('1496.5072'), Decimal('-1956.1714')),
 (49862, Decimal('5033.7347'), Decimal('1581.0561')),
 (49863, Decimal('120.2717'), Decimal('-3332.4069')),
 (49864, Decimal('51698.8941'), Decimal('48246.2155')),
 (49865, Decimal('47877.7887'), Decimal('44425.1101')),
 (49866, Decimal('138.3392'), Decimal('-3314.3394')),
 (49867, Decimal('207.7582'), Decimal('-3244.9204')),
 (49868, Decimal('1703.6956'), Decimal('-1748.9830')),
 (49869, Decimal('43499.6005'), Decimal('40046.9219')),
 (49870, Decimal('64070.2608'), Decimal('60617.5822')),
 (49871, Decimal('5955.3750'), Decimal('2502.6964')),
 (49872, Decimal('675.8956'), Decimal('-2776.7830')),
 (49873, Decimal('1428.9829'), Decimal('-2023.6957')),
 (49874, Decimal('574.2275'), Decimal('-2878.4511')),
 (49875, Decimal('610.3671'), Decimal('-2842.3115')),
 (49876, Decimal('13271.8022'), Decimal('9819.1236')),
 (49877, Decimal('41074.2798'), Decimal('37621.6012')),
 (49878, Decimal('5143.1463'), Decimal('1690.4677')),
 (49879, Decimal('88289.6649'), Decimal('84836.9863')),
 (49880, Decimal('378.3826'), Decimal('-3074.2960')),
 (49881, Decimal('1473.8636'), Decimal('-1978.8150')),
 (49882, Decimal('64.2420'), Decimal('-3388.4366')),
 (49883, Decimal('100.2242'), Decimal('-3352.4544')),
 (49884, Decimal('110266.9588'), Decimal('106814.2802')),
 (49885, Decimal('4793.4384'), Decimal('1340.7598')),
 (49886, Decimal('3301.4545'), Decimal('-151.2241')),
 (49887, Decimal('3941.2621'), Decimal('488.5835')),
 (49888, Decimal('108780.5231'), Decimal('105327.8445')),
 (49889, Decimal('8051.2699'), Decimal('4598.5913')),
 (49890, Decimal('48088.1391'), Decimal('44635.4605')),
 (49891, Decimal('48031.1479'), Decimal('44578.4693')),
 (49892, Decimal('1090.0970'), Decimal('-2362.5816')),
 (49893, Decimal('35799.5803'), Decimal('32346.9017')),
 (49894, Decimal('45355.5010'), Decimal('41902.8224')),
 (50189, Decimal('33857.8574'), Decimal('30405.1788')),
 (50190, Decimal('861.7436'), Decimal('-2590.9350')),
 (50191, Decimal('45640.7566'), Decimal('42188.0780')),
 (50192, Decimal('5871.3955'), Decimal('2418.7169')),
 (50193, Decimal('7114.6418'), Decimal('3661.9632')),
 (50194, Decimal('1586.9642'), Decimal('-1865.7144')),
 (50195, Decimal('33424.4453'), Decimal('29971.7667')),
 (50196, Decimal('674.6091'), Decimal('-2778.0695')),
 (50197, Decimal('3623.6228'), Decimal('170.9442')),
 (50198, Decimal('4168.1926'), Decimal('715.5140')),
 (50199, Decimal('26880.0159'), Decimal('23427.3373')),
 (50200, Decimal('6310.6152'), Decimal('2857.9366')),
 (50201, Decimal('2115.9522'), Decimal('-1336.7264')),
 (50202, Decimal('2870.2887'), Decimal('-582.3899')),
 (50203, Decimal('44568.1608'), Decimal('41115.4822')),
 (50204, Decimal('109900.1475'), Decimal('106447.4689')),
 (50205, Decimal('5913.1963'), Decimal('2460.5177')),
 (50206, Decimal('67397.5226'), Decimal('63944.8440')),
 (50207, Decimal('831.4763'), Decimal('-2621.2023')),
 (50208, Decimal('106618.2647'), Decimal('103165.5861')),
 (50209, Decimal('34032.6119'), Decimal('30579.9333')),
 (50210, Decimal('41541.2660'), Decimal('38088.5874')),
 (50211, Decimal('11026.5658'), Decimal('7573.8872')),
 (50212, Decimal('7505.7333'), Decimal('4053.0547')),
 (50213, Decimal('30414.7407'), Decimal('26962.0621')),
 (50214, Decimal('57109.5364'), Decimal('53656.8578')),
 (50215, Decimal('4269.7398'), Decimal('817.0612')),
 (50216, Decimal('1668.3751'), Decimal('-1784.3035')),
 (50217, Decimal('36470.7048'), Decimal('33018.0262')),
 (50218, Decimal('38396.7906'), Decimal('34944.1120')),
 (50219, Decimal('499.7973'), Decimal('-2952.8813')),
 (50220, Decimal('13982.5451'), Decimal('10529.8665')),
 (50221, Decimal('50675.1074'), Decimal('47222.4288')),
 (50222, Decimal('105304.6547'), Decimal('101851.9761')),
 (50223, Decimal('1785.9677'), Decimal('-1666.7109')),
 (50224, Decimal('4503.9283'), Decimal('1051.2497')),
 (50225, Decimal('76290.2841'), Decimal('72837.6055')),
 (50226, Decimal('63265.6899'), Decimal('59813.0113')),
 (50228, Decimal('31881.2921'), Decimal('28428.6135')),
 (50229, Decimal('2819.5151'), Decimal('-633.1635')),
 (50230, Decimal('9092.0796'), Decimal('5639.4010')),
 (50231, Decimal('51539.5098'), Decimal('48086.8312')),
 (50232, Decimal('29476.6233'), Decimal('26023.9447')),
 (50233, Decimal('4356.2067'), Decimal('903.5281')),
 (50234, Decimal('578.8425'), Decimal('-2873.8361')),
 (50235, Decimal('43345.4823'), Decimal('39892.8037')),
 (50236, Decimal('30210.3553'), Decimal('26757.6767')),
 (50237, Decimal('33995.3162'), Decimal('30542.6376')),
 (50238, Decimal('177.7078'), Decimal('-3274.9708')),
 (50239, Decimal('1956.8328'), Decimal('-1495.8458')),
 (50240, Decimal('74.0972'), Decimal('-3378.5814')),
 (50241, Decimal('171.0453'), Decimal('-3281.6333')),
 (50242, Decimal('41102.9221'), Decimal('37650.2435')),
 (50243, Decimal('22677.1243'), Decimal('19224.4457')),
 (50244, Decimal('48618.2545'), Decimal('45165.5759')),
 (50245, Decimal('35492.4603'), Decimal('32039.7817')),
 (50246, Decimal('29355.1061'), Decimal('25902.4275')),
 (50247, Decimal('1384.3708'), Decimal('-2068.3078')),
 (50248, Decimal('1006.6991'), Decimal('-2445.9795')),
 (50249, Decimal('16066.2511'), Decimal('12613.5725')),
 (50250, Decimal('3364.0770'), Decimal('-88.6016')),
 (50251, Decimal('610.3671'), Decimal('-2842.3115')),
 (50252, Decimal('107441.6818'), Decimal('103989.0032')),
 (50253, Decimal('4516.4918'), Decimal('1063.8132')),
 (50254, Decimal('528.9880'), Decimal('-2923.6906')),
 (50255, Decimal('49.7250'), Decimal('-3402.9536')),
 (50256, Decimal('96.3630'), Decimal('-3356.3156')),
 (50257, Decimal('366.4694'), Decimal('-3086.2092')),
 (50258, Decimal('190.1490'), Decimal('-3262.5296')),
 (50259, Decimal('52909.4126'), Decimal('49456.7340')),
 (50260, Decimal('8616.3793'), Decimal('5163.7007')),
 (50261, Decimal('6166.6034'), Decimal('2713.9248')),
 (50262, Decimal('203.0945'), Decimal('-3249.5841')),
 (50263, Decimal('34077.7439'), Decimal('30625.0653')),
 (50264, Decimal('4421.5909'), Decimal('968.9123')),
 (50265, Decimal('51614.1692'), Decimal('48161.4906')),
 (50266, Decimal('6210.2198'), Decimal('2757.5412')),
 (50267, Decimal('1384.3708'), Decimal('-2068.3078')),
 (50268, Decimal('593.2300'), Decimal('-2859.4486')),
 (50269, Decimal('1943.4035'), Decimal('-1509.2751')),
 (50270, Decimal('87934.4987'), Decimal('84481.8201')),
 (50271, Decimal('675.8956'), Decimal('-2776.7830')),
 (50272, Decimal('50545.3229'), Decimal('47092.6443')),
 (50273, Decimal('840.6560'), Decimal('-2612.0226')),
 (50274, Decimal('2467.5907'), Decimal('-985.0879')),
 (50275, Decimal('5771.7407'), Decimal('2319.0621')),
 (50276, Decimal('12941.4578'), Decimal('9488.7792')),
 (50277, Decimal('2871.5617'), Decimal('-581.1169')),
 (50278, Decimal('366.4694'), Decimal('-3086.2092')),
 (50279, Decimal('504.7245'), Decimal('-2947.9541')),
 (50280, Decimal('37858.4689'), Decimal('34405.7903')),
 (50281, Decimal('5072.0424'), Decimal('1619.3638')),
 (50282, Decimal('37862.7625'), Decimal('34410.0839')),
 (50283, Decimal('5614.5544'), Decimal('2161.8758')),
 (50284, Decimal('50427.1246'), Decimal('46974.4460')),
 (50285, Decimal('319.9083'), Decimal('-3132.7703')),
 (50286, Decimal('366.4694'), Decimal('-3086.2092')),
 (50287, Decimal('207.7582'), Decimal('-3244.9204')),
 (50288, Decimal('729.6412'), Decimal('-2723.0374')),
 (50289, Decimal('118581.3375'), Decimal('115128.6589')),
 (50290, Decimal('42053.3346'), Decimal('38600.6560')),
 (50291, Decimal('685.6020'), Decimal('-2767.0766')),
 (50292, Decimal('46436.3936'), Decimal('42983.7150')),
 (50293, Decimal('25864.8386'), Decimal('22412.1600')),
 (50294, Decimal('33679.3075'), Decimal('30226.6289')),
 (50295, Decimal('28442.9992'), Decimal('24990.3206')),
 (50296, Decimal('3173.9282'), Decimal('-278.7504')),
 (50297, Decimal('116390.7349'), Decimal('112938.0563')),
 (50298, Decimal('46905.3158'), Decimal('43452.6372')),
 (50299, Decimal('925.1855'), Decimal('-2527.4931')),
 (50300, Decimal('681.5586'), Decimal('-2771.1200')),
 (50301, Decimal('47893.0954'), Decimal('44440.4168')),
 (50302, Decimal('13179.0815'), Decimal('9726.4029')),
 (50303, Decimal('84.5295'), Decimal('-3368.1491')),
 (50304, Decimal('104751.3605'), Decimal('101298.6819')),
 (50305, Decimal('729.6412'), Decimal('-2723.0374')),
 (50306, Decimal('36308.0778'), Decimal('32855.3992')),
 (50307, Decimal('3697.8193'), Decimal('245.1407')),
 (50308, Decimal('2946.4492'), Decimal('-506.2294')),
 (50309, Decimal('223.6817'), Decimal('-3228.9969')),
 (50310, Decimal('78560.8142'), Decimal('75108.1356')),
 (50311, Decimal('28963.5634'), Decimal('25510.8848')),
 (50312, Decimal('76861.5747'), Decimal('73408.8961')),
 (50313, Decimal('59784.6491'), Decimal('56331.9705')),
 (50314, Decimal('51438.0899'), Decimal('47985.4113')),
 (50315, Decimal('21263.9208'), Decimal('17811.2422')),
 (50316, Decimal('7550.2288'), Decimal('4097.5502')),
 (50317, Decimal('1074.5510'), Decimal('-2378.1276')),
 (50318, Decimal('228.5340'), Decimal('-3224.1446')),
 (50319, Decimal('881.8229'), Decimal('-2570.8557')),
 (50320, Decimal('675.8956'), Decimal('-2776.7830')),
 (50321, Decimal('49740.9593'), Decimal('46288.2807')),
 (50322, Decimal('80639.0422'), Decimal('77186.3636')),
 (50658, Decimal('6876.8446'), Decimal('3424.1660')),
 (50659, Decimal('1460.5312'), Decimal('-1992.1474')),
 (50660, Decimal('25.3868'), Decimal('-3427.2918')),
 (50661, Decimal('33230.9334'), Decimal('29778.2548')),
 (50662, Decimal('38268.8819'), Decimal('34816.2033')),
 (50663, Decimal('98476.8845'), Decimal('95024.2059')),
 (50664, Decimal('47807.3096'), Decimal('44354.6310')),
 (50665, Decimal('242.4277'), Decimal('-3210.2509')),
 (50666, Decimal('104.7480'), Decimal('-3347.9306')),
 (50667, Decimal('12880.6060'), Decimal('9427.9274')),
 (50668, Decimal('66963.2766'), Decimal('63510.5980')),
 (50669, Decimal('4200.0046'), Decimal('747.3260')),
 (50670, Decimal('589.1239'), Decimal('-2863.5547')),
 (50671, Decimal('25906.2943'), Decimal('22453.6157')),
 (50672, Decimal('88914.2997'), Decimal('85461.6211')),
 (50673, Decimal('46374.7515'), Decimal('42922.0729')),
 (50674, Decimal('364.8386'), Decimal('-3087.8400')),
 (50675, Decimal('43214.8509'), Decimal('39762.1723')),
 (50676, Decimal('39281.3353'), Decimal('35828.6567')),
 (50677, Decimal('2150.6110'), Decimal('-1302.0676')),
 (50678, Decimal('18956.8341'), Decimal('15504.1555')),
 (50679, Decimal('436.2922'), Decimal('-3016.3864')),
 (50680, Decimal('2083.3668'), Decimal('-1369.3118')),
 (50681, Decimal('42597.7826'), Decimal('39145.1040')),
 (50682, Decimal('43665.7360'), Decimal('40213.0574')),
 (50683, Decimal('117819.3126'), Decimal('114366.6340')),
 (50684, Decimal('8793.3479'), Decimal('5340.6693')),
 (50685, Decimal('7461.9423'), Decimal('4009.2637')),
 (50686, Decimal('1689.0125'), Decimal('-1763.6661')),
 (50687, Decimal('41847.2423'), Decimal('38394.5637')),
 (50688, Decimal('65492.6682'), Decimal('62039.9896')),
 (50689, Decimal('52087.7772'), Decimal('48635.0986')),
 (50690, Decimal('2768.7414'), Decimal('-683.9372')),
 (50691, Decimal('207.7582'), Decimal('-3244.9204')),
 (50692, Decimal('4183.2730'), Decimal('730.5944')),
 (50693, Decimal('36241.7955'), Decimal('32789.1169')),
 (50694, Decimal('107452.3406'), Decimal('103999.6620')),
 (50695, Decimal('472.7093'), Decimal('-2979.9693')),
 (50696, Decimal('53143.2411'), Decimal('49690.5625')),
 (50697, Decimal('8851.9764'), Decimal('5399.2978')),
 (50698, Decimal('29789.8400'), Decimal('26337.1614')),
 (50699, Decimal('32553.0847'), Decimal('29100.4061')),
 (50700, Decimal('202.3635'), Decimal('-3250.3151')),
 (50701, Decimal('873.7259'), Decimal('-2578.9527')),
 (50702, Decimal('39360.9687'), Decimal('35908.2901')),
 (50703, Decimal('65363.8828'), Decimal('61911.2042')),
 (50704, Decimal('13824.8635'), Decimal('10372.1849')),
 (50705, Decimal('12119.3876'), Decimal('8666.7090')),
 (50706, Decimal('11159.7159'), Decimal('7707.0373')),
 (50707, Decimal('4190.2831'), Decimal('737.6045')),
 (50708, Decimal('5976.6219'), Decimal('2523.9433')),
 (50709, Decimal('2768.7414'), Decimal('-683.9372')),

#### Convert row object into DataFrame object

In [21]:
# Short syntax of for loop
# cursor.description >> It is a sequence of Column instances, each one describing one result column in order.
# Create a list of all column names

[col[0] for col in cursor.description]

# col_names = [col[0] for col in cursor.description]

In [22]:
# Convert structured or record ndarray to DataFrame

df = pd.DataFrame.from_records(rows, columns=col_names)
df

      SalesOrderID    TotalDue DistFromAvg
0            49443     76.2853  -3376.3933
1            49444   7333.3076   3880.6290
2            49445   3173.9282   -278.7504
3            49446  15340.6533  11887.9747
4            49447    120.2717  -3332.4069
...            ...         ...         ...
3360         63351   1379.9572  -2072.7214
3361         63352   2710.6092   -742.0694
3362         63353   2728.3003   -724.3783
3363         63361   2634.3974   -818.2812
3364         63362   2673.0613   -779.6173

[3365 rows x 3 columns]

In [23]:
# Close all connections
cursor.close()
conn.close()