<img height="100" src="logotmg.png" width="900" alt="Talia Morchi" id="tmg_logo" title="Data Analyst Course">
<center><h1><u>Welcome to the python for data analysis course </u></h1></center><center><h2>Class 4+5</h2></center>

In [ ]:
import pandas as pd
import numpy as np

# Import data source

In [ ]:
# Import csv file
# Watch sample from the data
df = pd.read_csv ('police.csv', parse_dates=['stop_date'])
df['stop_year'] = df['stop_date'].dt.year
df.head(3)

,stop_date,stop_time,county_name,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,ticket_amount,stop_duration,drugs_related_stop,stop_year
0,2005-02-01,1:55,NaN,M,1985.0,20.0,White,Speeding,Speeding,False,NaN,Ticket,False,341.0,0-15 Min,False,2005
1,2005-01-18,8:15,NaN,M,1965.0,40.0,White,Speeding,Speeding,False,NaN,Citation,False,NaN,0-15 Min,False,2005
2,2005-01-23,23:15,NaN,M,1972.0,33.0,White,Speeding,Speeding,False,NaN,Ticket,False,161.0,0-15 Min,False,2005

## Pivot Tables

The function pivot_table() can be used to create spreadsheet-style pivot tables

* **values**: a column or a list of columns to aggregate

* **index**: a column to group by on the pivot table index

* **columns**: a column to group by on the pivot table column

* **aggfunc**: function to use for aggregation, defaulting to numpy.mean

In [ ]:
# For each gender, check how many violation were from each type

df.pivot_table(values='stop_year', index='violation_raw', columns='driver_gender', aggfunc='count')

driver_gender                         F      M
violation_raw
APB                                  21     58
Call for Service                    436    862
Equipment/Inspection Violation     2487   8533
Motorist Assist/Courtesy             61    142
Other Traffic Violation            3204  13020
Registration Violation             1013   2419
Seatbelt Violation                  635   2317
Special Detail/Directed Patrol      107   2348
Speeding                          15482  32979
Suspicious Person                    15     41
Violation of City/Town Ordinance     46    165
Warrant                               4     11

In [ ]:
# Make the pivot table just on the last 3 years

mask = df['stop_year'] >= 2013
df[mask].pivot_table(values='stop_date', index='violation_raw', columns=['driver_gender', 'stop_year'], aggfunc='count')

driver_gender                          F                       M          \
stop_year                           2013    2014    2015    2013    2014
violation_raw
APB                                  3.0     4.0     2.0     6.0     4.0
Call for Service                    46.0    42.0    86.0    69.0    99.0
Equipment/Inspection Violation     308.0   388.0   377.0  1108.0  1176.0
Motorist Assist/Courtesy             7.0     7.0     7.0     7.0    20.0
Other Traffic Violation            321.0   373.0   344.0  1038.0  1127.0
Registration Violation             108.0   116.0   155.0   207.0   247.0
Seatbelt Violation                 170.0   238.0   226.0   506.0   970.0
Special Detail/Directed Patrol       7.0     3.0     2.0    16.0    10.0
Speeding                          1195.0  1346.0  1183.0  2281.0  2657.0
Suspicious Person                    NaN     4.0     NaN     4.0     5.0
Violation of City/Town Ordinance     2.0     2.0     4.0    11.0    10.0
Warrant                              NaN     NaN     1.0     1.0     1.0

driver_gender
stop_year                           2015
violation_raw
APB                                  8.0
Call for Service                   154.0
Equipment/Inspection Violation    1064.0
Motorist Assist/Courtesy            17.0
Other Traffic Violation            999.0
Registration Violation             343.0
Seatbelt Violation                 822.0
Special Detail/Directed Patrol      34.0
Speeding                          2385.0
Suspicious Person                    4.0
Violation of City/Town Ordinance    12.0
Warrant                              2.0

<img height="100" src="time_to_practice.png" width="200" alt="Hands on" id="prc_time" title="Data Analyst Course">
<center><h1>Class Practice 4.1</h1></center>

1. How many men/women have been arrested after committing an violation in the last three years? Display in separate columns for each year and gender

2. Please show in what decade of life were the most offenses committed. Display separate columns for each gender:
    * Run the folowing code first:
            df['age_decade'] = df.driver_age.apply (lambda x : str (x)[:-3] + '0s')
            (We will understand this code in the next notebook)
    * You can use any of the tools we learned so far
    * In what decade people tend to commit more violations?

=========================================================================================

#### Pactice 4.1 - Solution
1. How many men/women have been arrested after committing an violation in the last three years? Display in separate columns for each year and gender

2. Please show in what decade of life were the most offenses committed. Display separate columns for each gender:
    * Run the folowing code first:
            df['age_decade'] = df.driver_age.apply (lambda x : str (x)[:-3] + '0s')
            (We will understand this code in the next notebook)
    * You can use any of the tools we learned so far
    * In what decade people tend to commit more violations?

In [ ]:
# 1
# Compare how many f/m were arrested after violation in the last 3 years

mask = df['stop_year'] >= 2013

df[mask].pivot_table(values='stop_date', index='is_arrested', columns=['stop_year', 'driver_gender'], aggfunc='count')

stop_year      2013        2014        2015
driver_gender     F     M     F     M     F     M
is_arrested
False          2125  5095  2478  6132  2345  5666
True             42   159    45   194    42   178

In [ ]:
# 2
# Add new column of decade by applying lambda function on all the df
df['age_decade'] = df.driver_age.apply (lambda x : str (x)[:-3] + '0s')
df['age_decade']

0        20s
1        40s
2        30s
3        10s
4        20s
        ...
91736    20s
91737    30s
91738    20s
91739    20s
91740    50s
Name: age_decade, Length: 91741, dtype: object

In [ ]:
# Pivot table as rewuested
df.pivot_table(values='stop_date', index='age_decade', columns='driver_gender', aggfunc='count')

driver_gender      F      M
age_decade
0s                47    246
10s             1709   3887
20s            10475  24513
30s             4916  14054
40s             3607  10515
50s             2064   6798
60s              588   2335
70s               88    480
80s               16     65
90s                1      2

In [ ]:
# We can clearlt see that on their 20s, they tend to commit more violations