<img height="100" src="logotmg.png" width="900" alt="Talia Morchi" id="tmg_logo" title="Data Analyst Course">
<center><h1><u>Welcome to the python for data analysis course </u></h1></center><center><h2>Class 4+5</h2></center>

<img height="100" src="time_to_practice.png" width="200" alt="Hands on" id="prc_time" title="Data Analyst Course">
<center><h1>Summary practice - Solution</h1></center>

### Titanic dataset exercise

#### 1. Import Titanic dataset from csv file and run python describe function

#### Dataset column explanation:

PassengerId: Id of every passenger

Pclass: There are 3 classes of passengers. Class1 (best one), Class2 and Class3 

Survived: This feature have value 0 and 1. 0 = not survived, 1 for = survived.

Name: Name of passenger

Sex: Gender of passenger.

Age: Age of passenger.

SibSp: number of siblings or spouses abroad the titanic.

Parch: number of parents/children abroad the titanic

Ticket: Ticket no number.

Fare: passenger fare.

Cabin: The cabin number of passenger.

Embarked: port of embarkation C=Cherbourg, Q=Queenstown S=Southampton.

home.dest: The passanger destination

In [1]:
import pandas as pd
import numpy as np
import math
df = pd.read_csv('titanic_train.csv',sep=',')
df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [2]:
df.shape

(891, 12)

In [3]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

#### 2. Select name and fare columns

In [4]:
df[ ['Name','Fare'] ].head(5)
#df.loc[0:2,['Name','Fare']]

                                                Name     Fare
0                            Braund, Mr. Owen Harris   7.2500
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  71.2833
2                             Heikkinen, Miss. Laina   7.9250
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  53.1000
4                           Allen, Mr. William Henry   8.0500

#### 3. How many passengers (rows) have age higher than 18?

In [5]:
mask = df['Age'] > 18
df[mask]['PassengerId'].count()

575

#### 4. Select all female passengers. How many passengers are? What is their average fare value?

In [6]:
mask = df['Sex'] == 'female'
df[mask]['PassengerId'].count()

314

In [7]:
# option 1
df.groupby('Sex')[['Fare']].mean()
# option 2
df.groupby('Sex').agg({'Fare':['count','mean'],
                        'Age':['mean']})

# mask = df['Sex']=='female'
# df[mask].groupby('Sex').agg({'Fare':'mean'})

        Fare                   Age
       count       mean       mean
Sex
female   314  44.479818  27.915709
male     577  25.523893  30.726645

#### 5. Select those who survived and their name begins with 'C' or 'c'

In [8]:
str_upper = df['Name'].str.upper().str[0]

# Option 1
df[(df['Survived']==1) & (str_upper=='C')]#.count()

# Option 2
mask1 = df['Survived']==1
mask2 = str_upper=='C'
df[mask1 & mask2]#.count()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.00,1,0,PC 17599,71.2833,C85,C
78,79,1,2,"Caldwell, Master. Alden Gates",male,0.83,0,2,248738,29.0000,NaN,S
166,167,1,1,"Chibnall, Mrs. (Edith Martha Bowerman)",female,NaN,0,1,113505,55.0000,E33,S
204,205,1,3,"Cohen, Mr. Gurshon ""Gus""",male,18.00,0,0,A/5 3540,8.0500,NaN,S
208,209,1,3,"Carr, Miss. Helen ""Ellen""",female,16.00,0,0,367231,7.7500,NaN,Q
211,212,1,2,"Cameron, Miss. Clear Annie",female,35.00,0,0,F.C.C. 13528,21.0000,NaN,S
237,238,1,2,"Collyer, Miss. Marjorie ""Lottie""",female,8.00,0,2,C.A. 31921,26.2500,NaN,S
257,258,1,1,"Cherry, Miss. Gladys",female,30.00,0,0,110152,86.5000,B77,S
289,290,1,3,"Connolly, Miss. Kate",female,22.00,0,0,370373,7.7500,NaN,Q
323,324,1,2,"Caldwell, Mrs. Albert Francis (Sylvia Mae Harb...",female,22.00,1,1,248738,29.0000,NaN,S
348,349,1,3,"Coutts, Master. William Loch ""William""",male,3.00,1,1,C.A. 37671,15.9000,NaN,S
390,391,1,1,"Carter, Mr. William Ernest",male,36.00,1,2,113760,120.0000,B96 B98,S
426,427,1,2,"Clarke, Mrs. Charles V (Ada Maria Winfield)",female,28.00,1,0,2003,26.0000,NaN,S
435,436,1,1,"Carter, Miss. Lucile Polk",female,14.00,1,2,113760,120.0000,B96 B98,S
489,490,1,3,"Coutts, Master. Eden Leslie ""Neville""",male,9.00,1,1,C.A. 37671,15.9000,NaN,S
540,541,1,1,"Crosby, Miss. Harriet R",female,36.00,0,2,WE/P 5735,71.0000,B22,S
580,581,1,2,"Christy, Miss. Julie Rachel",female,25.00,1,1,237789,30.0000,NaN,S
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.00,0,1,PC 17755,512.3292,B51 B53 B55,C
707,708,1,1,"Calderhead, Mr. Edward Pennington",male,42.00,0,0,PC 17476,26.2875,E24,S
708,709,1,1,"Cleaver, Miss. Alice",female,22.00,0,0,113781,151.5500,NaN,S
724,725,1,1,"Chambers, Mr. Norman Campbell",male,27.00,1,0,113806,53.1000,E8,S
763,764,1,1,"Carter, Mrs. William Ernest (Lucile Polk)",female,36.00,1,2,113760,120.0000,B96 B98,S
801,802,1,2,"Collyer, Mrs. Harvey (Charlotte Annie Tate)",female,31.00,1,1,C.A. 31921,26.2500,NaN,S
802,803,1,1,"Carter, Master. William Thornton II",male,11.00,1,2,113760,120.0000,B96 B98,S
809,810,1,1,"Chambers, Mrs. Norman Campbell (Bertha Griggs)",female,33.00,1,0,113806,53.1000,E8,S
835,836,1,1,"Compton, Miss. Sara Rebecca",female,39.00,1,1,PC 17756,83.1583,E49,C
838,839,1,3,"Chip, Mr. Chang",male,32.00,0,0,1601,56.4958,NaN,S

#### 6. Replace null values in the column with the highest count of nulls, with the mean value of that column

In [9]:
# get nulls count per column - Cabin has the highest count, BUT IT'S NOT A NUMBER SO IT DOESN'T HAVE MEAN!
# the relevant column: Age
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [10]:
#df['Cabin'] = df['Cabin'].fillna(df['Cabin'].mean()) 
df['Age'] = df['Age'].fillna(df['Age'].mean()) 
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.000000,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.000000,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.000000,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,29.699118,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.000000,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.000000,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.000000,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.000000,1,0,237736,30.0708,NaN,C

#### 7. Add new column named 'Fare_rounded' which will be a round of 'Fare', make sure it's a finite column in the dataframe

In [11]:
# Option 1
df['Fare_rounded'] = df['Fare'].astype(int)

# Option 2
df['Fare_rounded'] = df['Fare'].round(0)
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare_rounded
0,1,0,3,"Braund, Mr. Owen Harris",male,22.000000,1,0,A/5 21171,7.2500,NaN,S,7.0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,1,0,PC 17599,71.2833,C85,C,71.0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.000000,0,0,STON/O2. 3101282,7.9250,NaN,S,8.0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,1,0,113803,53.1000,C123,S,53.0
4,5,0,3,"Allen, Mr. William Henry",male,35.000000,0,0,373450,8.0500,NaN,S,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.000000,0,0,211536,13.0000,NaN,S,13.0
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.000000,0,0,112053,30.0000,B42,S,30.0
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.699118,1,2,W./C. 6607,23.4500,NaN,S,23.0
889,890,1,1,"Behr, Mr. Karl Howell",male,26.000000,0,0,111369,30.0000,C148,C,30.0
890,891,0,3,"Dooley, Mr. Patrick",male,32.000000,0,0,370376,7.7500,NaN,Q,8.0

#### 8. Add new column named 'age_decade' which is defined as a decade category of the age column:
#### e.g.: 23 -> '20+', 46 -> '40+' etc.   
#### (before doing so drop all rows with null ages)

In [12]:
#drop nulls of age - we don't have nulls since we replaced it with mean in previous ex
df.dropna(subset=['Age'],inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 0 to 890
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PassengerId   891 non-null    int64
 1   Survived      891 non-null    int64
 2   Pclass        891 non-null    int64
 3   Name          891 non-null    object
 4   Sex           891 non-null    object
 5   Age           891 non-null    float64
 6   SibSp         891 non-null    int64
 7   Parch         891 non-null    int64
 8   Ticket        891 non-null    object
 9   Fare          891 non-null    float64
 10  Cabin         204 non-null    object
 11  Embarked      889 non-null    object
 12  Fare_rounded  891 non-null    float64
dtypes: float64(3), int64(5), object(5)
memory usage: 97.5+ KB

In [13]:
def toDecade(age):
    for i in range(10):
        print(str(int(age/10) * 10)+'+'+str(i))
        #return str(int(age/10) * 10)+'+'+str(i)

# test function
toDecade(34)

30+0
30+1
30+2
30+3
30+4
30+5
30+6
30+7
30+8
30+9

In [14]:
# 1st option with a function
#df['age_decade'] = df['Age'].apply(toDecade)

# 2nd option with a lambda
df['age_decade'] = df['Age'].apply(lambda age: str(int(age/10) * 10)+'+' )
df['age_decade']

0      20+
1      30+
2      20+
3      30+
4      30+
      ...
886    20+
887    10+
888    20+
889    20+
890    30+
Name: age_decade, Length: 891, dtype: object

In [15]:
df[['Age','age_decade']].head(5)

    Age age_decade
0  22.0        20+
1  38.0        30+
2  26.0        20+
3  35.0        30+
4  35.0        30+

#### 9A. Group by the new created column 'age_decade', aggragating: mean and count  over columns 'survived' & 'fare'
#### 9B. Group by column 'sex', aggragating: mean, count and std over column 'survived'

In [16]:
df.groupby('age_decade').agg({'Survived':['count','mean'],
                              'Fare':['count','mean','std']})

           Survived            Fare
              count      mean count       mean        std
age_decade
0+               62  0.612903    62  30.576679  25.195357
10+             102  0.401961   102  32.535132  50.481289
20+             397  0.324937   397  24.996052  39.221049
30+             167  0.437126   167  40.377294  73.480663
40+              89  0.382022    89  38.002297  43.655363
50+              48  0.416667    48  47.933333  48.963156
60+              19  0.315789    19  48.367542  58.008160
70+               6  0.000000     6  30.197233  26.275864
80+               1  1.000000     1  30.000000        NaN

In [17]:
df.groupby('Sex').agg({'Survived':['count','sum','mean','std']})

       Survived
          count  sum      mean       std
Sex
female      314  233  0.742038  0.438211
male        577  109  0.188908  0.391775

#### 10. Create a new partial dataframe from titanic with females only (make it a copy). 
#### merge the original df as the strong side of a 'left join', the key will be passenger id, leave all original df columns and only passenger id column of new female df, rename the column.

In [18]:
mask = df['Sex']=='female'
df_female = df[mask].copy()

In [19]:
df_female['PassengerId_rkey'] = df_female['PassengerId']
df_female.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare_rounded,age_decade,PassengerId_rkey
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,71.0,30+,2
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,8.0,20+,3
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,53.0,30+,4

In [20]:

df_mrg = pd.merge(df, df_female[['PassengerId_rkey']]
                  ,how='left'
                  ,left_on=['PassengerId']
                  ,right_on=['PassengerId_rkey']
                  ,indicator=True) #indicator: the source of the row (left or both)
df_mrg

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare_rounded,age_decade,PassengerId_rkey,_merge
0,1,0,3,"Braund, Mr. Owen Harris",male,22.000000,1,0,A/5 21171,7.2500,NaN,S,7.0,20+,NaN,left_only
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,1,0,PC 17599,71.2833,C85,C,71.0,30+,2.0,both
2,3,1,3,"Heikkinen, Miss. Laina",female,26.000000,0,0,STON/O2. 3101282,7.9250,NaN,S,8.0,20+,3.0,both
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,1,0,113803,53.1000,C123,S,53.0,30+,4.0,both
4,5,0,3,"Allen, Mr. William Henry",male,35.000000,0,0,373450,8.0500,NaN,S,8.0,30+,NaN,left_only
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.000000,0,0,211536,13.0000,NaN,S,13.0,20+,NaN,left_only
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.000000,0,0,112053,30.0000,B42,S,30.0,10+,888.0,both
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.699118,1,2,W./C. 6607,23.4500,NaN,S,23.0,20+,889.0,both
889,890,1,1,"Behr, Mr. Karl Howell",male,26.000000,0,0,111369,30.0000,C148,C,30.0,20+,NaN,left_only
890,891,0,3,"Dooley, Mr. Patrick",male,32.000000,0,0,370376,7.7500,NaN,Q,8.0,30+,NaN,left_only