<img height='100' src='logotmg.png' width='900' alt='Talia Morchi' id='tmg_logo' title='Data Analyst Course'>
<center><h1><u>Welcome to the python for data analysis course </u></h1></center><center><h2>Class 8</h2></center>

In [1]:
import numpy as np
import pandas as pd

In [2]:
np_data = np.random.randint(0, 100, (1000, 50))

In [3]:
df = pd.DataFrame(np_data)
df.tail(3)

,0,1,2,3,4,5,6,7,8,9,...,40,41,42,43,44,45,46,47,48,49
997,12,41,6,52,6,79,94,56,57,53,...,44,49,70,0,86,59,20,30,40,52
998,58,86,76,37,89,90,38,34,41,13,...,18,6,70,66,49,21,9,87,59,19
999,58,9,30,60,51,53,65,65,86,67,...,53,64,25,65,27,22,6,84,90,69

## Changing Options

#### Show how many rows/columns to show

In [4]:
pd.options.display.max_columns
# pd.options.display.max_rows

20

#### Same result in different way

In [5]:
pd.get_option('max_columns')
# pd.get_option('max_rows')

20

In [11]:
pd.set_option('max_columns', 16)
pd.set_option('max_rows', 4)

In [12]:
df

     0   1   2   3   4   5   6   7   ...  42  43  44  45  46  47  48  49
0    90  20   7  88  55  14  42   8  ...  90  43  49   2  55  30   8  94
1    50  22   4  62  30  32  11  60  ...  23  86  34  65  96  93  24  92
..   ..  ..  ..  ..  ..  ..  ..  ..  ...  ..  ..  ..  ..  ..  ..  ..  ..
998  58  86  76  37  89  90  38  34  ...  70  66  49  21   9  87  59  19
999  58   9  30  60  51  53  65  65  ...  25  65  27  22   6  84  90  69

[1000 rows x 50 columns]

In [8]:
pd.reset_option('max_columns')

In [9]:
pd.describe_option('max_columns')

display.max_columns : int
    If max_cols is exceeded, switch to truncate view. Depending on
    `large_repr`, objects are either centrally truncated or printed as
    a summary view. 'None' value means unlimited.

    In case python/IPython is running in a terminal and `large_repr`
    equals 'truncate' this can be set to 0 and pandas will auto-detect
    the width of the terminal and print a truncated object which fits
    the screen width. The IPython notebook, IPython qtconsole, or IDLE
    do not run in a terminal and hence it is not possible to do
    correct auto-detection.
    [default: 20] [currently: 20]

## Get Pandas version and update version

In [10]:
# Show pandas version
pd.__version__

'1.1.4'

#### In Anaconda prompt

Return all libraries with its versions
* pip list

Show information about library (here for pandas)
* pip show pandas

Upgrade version of library
* pip install -- upgrade pandas